package classic_cs_problems_in_Java;

import java.util.stream.IntStream;

public class Fib5 {
    private int last = 0, next = 1; //fib(0), fib(1)
    public IntStream stream() {
        // IntStream.generate() returns an infinite sequential unordered stream,
        // where each element is generated by the provideded IntSupplier
        // Java8提供了Stream.iterate()和Stream.generate()来生成无限流，这两个方法会根据给定的表达式来生成包含无限个数据的流，所以一般结合limit()来使用。
        // reference: https://developer.aliyun.com/article/949637
        return IntStream.generate(() ->{
            int oldLast = last;
            last = next;
            next = oldLast + next;
            return oldLast;
        });
    }
    public static void main(String[] args) {
        Fib5 fib5 = new Fib5();
        fib5.stream().limit(5).forEachOrdered(System.out::print);
    }
    
}